import { MetadataRoute } from 'next';

const BASE_URL = 'https://www.efssolar.co.nz';

const newsSlugs = [
    'about-the-national-electricity-market',
    'sleek-6-6kw-solar-system',
    'energy-efficient-6-6kw-solar-system',
    'long-lasting-6-6kw-solar-system',
    'durable-6-6kw-solar-system',
    'hybrid-6-6kw-solar-system',
    'technologically-advanced-6-6kw-solar-system',
    'eco-friendly-6-6kw-solar-system',
    'high-performing-6-6kw-solar-system',
    'innovative-6-6kw-solar-system',
    'futuristic-6-6kw-solar-system',
    'smart-6-6kw-solar-system',
    'classic-6-6kw-solar-system',
    'simple-6-6kw-solar-system',
    'modern-6-6kw-solar-system',
    'professional-6-6kw-solar-system',
    'top-rated-6-6kw-solar-system',
    'advanced-6-6kw-solar-system',
    'budget-6-6kw-solar-system',
    'compact-6-6kw-solar-system',
    'premium-6-6kw-solar-system',
    'large-6-6kw-solar-system',
    'commercial-6-6kw-solar-system',
    'residential-6-6kw-solar-system',
    'reliable-6-6kw-solar-system',
    'efficient-6-6kw-solar-system',
    'high-quality-6-6kw-solar-system',
    'affordable-6-6kw-solar-system',
    'new-energy-tech-consumer-code-program',
    'why-solar-power-is-the-future-of-energy-in-australia',
    'the-maintenance-and-lifespan-of-solar-panels',
    'solar-payment-options',
    'benefits-of-solar-power',
    'common-misconceptions-about-solar-power',
    'dodgy-solar-installers',
    'jobs-of-the-future-in-clean-energy',
    'how-are-solar-panels-tested',
    'what-is-neo-and-why-its-changing',
    'micro-inverters-do-i-need-them',
    'is-your-roof-solar-ready',
    'feed-in-tariffs-explained',
    'businesses-should-consider-solar',
    'australias-energy-supply-crisis',
    '5-biggest-solar-farms-in-the-world',
    'household-budgets',
    'vampire-appliances',
    'when-to-consider-going-solar',
    'solar-cowboys',
    'solar-myths',
    'investment-in-clean-energy',
];

export default function sitemap(): MetadataRoute.Sitemap {
    const newsPages: MetadataRoute.Sitemap = newsSlugs.map(slug => ({
        url: `${BASE_URL}/news/${slug}`,
        lastModified: new Date(),
        changeFrequency: 'yearly' as const,
        priority: 0.6,
    }));

    return [
        { url: BASE_URL, lastModified: new Date(), changeFrequency: 'weekly', priority: 1 },
        { url: `${BASE_URL}/services/residential-solar`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
        { url: `${BASE_URL}/services/commercial-solar`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
        { url: `${BASE_URL}/services/batteries`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
        { url: `${BASE_URL}/technology/tesla-powerwall`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
        { url: `${BASE_URL}/technology/energizer`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
        { url: `${BASE_URL}/technology/goodwe`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
        { url: `${BASE_URL}/reviews`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
        { url: `${BASE_URL}/reviews/oxenford-solar-system-upgrade`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.7 },
        { url: `${BASE_URL}/reviews/carrara-premium-solar-system-installation`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.7 },
        { url: `${BASE_URL}/reviews/solar-system-battery-replacement-at-nerang`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.7 },
        { url: `${BASE_URL}/about`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.6 },
        { url: `${BASE_URL}/contact`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.7 },
        { url: `${BASE_URL}/career`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5 },
        { url: `${BASE_URL}/get-started`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
        { url: `${BASE_URL}/solar-monitoring`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
        { url: `${BASE_URL}/news`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.8 },
        ...newsPages,
        { url: `${BASE_URL}/privacy-policy`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.2 },
        { url: `${BASE_URL}/terms-of-use`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.2 },
        { url: `${BASE_URL}/disclaimer`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.2 },
    ];
}
